### ISSUE TITLE
NullReferenceException when opening help for a command with 'string varname = null' parameter.

### ISSUE THREAD

**Issue by r44v** [bilal-fazlani/commanddotnet#97]
The CommandDotNet package throws a `NullReferenceException` when opening help (`-h`) for a command with a `string varname = null` parameter. The default value `null` seems to be the cause.

```
   at CommandDotNet.HelpGeneration.DetailedHelpTextProvider.<>c.<BuildOptions>b__5_3(CommandOption o)
   at CommandDotNet.HelpGeneration.DetailedHelpTextProvider.<>c__DisplayClass11_0`1.<GetColumnMaxLength>b__0(T o)
   at System.Linq.Enumerable.Max[TSource](IEnumerable`1 source, Func`2 selector)
   at CommandDotNet.HelpGeneration.DetailedHelpTextProvider.RenderParameter[T](List`1 arguments, T argument, Func`2 function)
   at CommandDotNet.HelpGeneration.DetailedHelpTextProvider.BuildOptions(ICommand app, StringBuilder usageBuilder)
   at CommandDotNet.HelpGeneration.DetailedHelpTextProvider.GetHelpText(ICommand app)
   at CommandDotNet.MicrosoftCommandLineUtils.CommandLineApplication.ShowHelp()
   at CommandDotNet.MicrosoftCommandLineUtils.CommandLineApplication.Execute(String[] args)
   at CommandDotNet.AppRunner`1.Run(String[] args)
   at xxxxx.Program.Main(String[] args) in C:\xxxxx\Program.cs:line 26
```
line 26 is the following call `return appRunner.Run(args);`

I am using the nuget provided version 2.7.5.

I've been able to work around this by changing `null` to an empty string, but it would be nice if this exception got handled.

**Comment by drewburlingame** [comment]
@r44v thanks for submitting this issue.  This is fixed in 2.7.16-beta.   We'll be keeping the beta postfix until we've fixed the other known bugs.

**Comment by r44v** [comment]
@drewburlingame Thanks for the (really) quick update, unfortunately it does not seem to have fixed the issue in my case. I've installed the latest beta but I still get the same exception. I've cleaned the project etc to be sure it were no cached filed that triggerd the exception.

**Comment by bilal-fazlani** [comment]
@r44v 
Could you please show your `App` methods and constructor?

**Comment by r44v** [comment]
The simplist version would be 

```csharp
static int Main(string[] args)
        {
            var appRunner = new AppRunner<HClient>();
            return appRunner.Run(args);
        }
```

```csharp
class HClient
    {
        public HClient(string settings = null, bool debug = false)
        {

        }
    }
```

This still gives the exception

**Comment by bilal-fazlani** [comment]
Thanks! I will check it out

**Comment by bilal-fazlani** [comment]
I can reproduce this error in 2.7.16-beta. However in the master, right now, it does not seem to be a problem. So I am just going to tag a new version and that should take care of it.

**Comment by bilal-fazlani** [comment]
https://www.nuget.org/packages/CommandDotNet/2.7.17-beta

**Comment by drewburlingame** [comment]
@r44v did this fix your bug?

**Comment by drewburlingame** [comment]
@r44v I'm going to close this issue.  Feel free to reopen it if you're still having issues.  We've just release [2.8.0](https://www.nuget.org/packages/CommandDotNet/2.8.0) with a number of enhancements.
